language: csharp
solution: gtd.sln
mono: none
dotnet: 3.1.302
before_install:
- openssl aes-256-cbc -K $encrypted_8f373cd25b57_key -iv $encrypted_8f373cd25b57_iv -in deploy_key.enc -out deploy_key -d
install:
- dotnet restore
script:
- dotnet build
- dotnet test
after_success:
- dotnet publish --runtime linux-x64 --configuration Release
- tar -czf package.tgz -C ./Source/Gtd.Web/bin/Release/netcoreapp3.1/linux-x64/publish .
before_deploy:
- chmod 600 ./deploy_key && mv deploy_key ~/.ssh/id_rsa
deploy:
- provider: script
  script: bash scripts/deploy.sh staging
  on:
    branch: master
after_deploy:
- rm ~/.ssh/id_rsa
- rm package.tgz
- rm -r ./Source/Gtd.Web/bin/Release/netcoreapp3.1/linux-x64/publish
